# Sample .travis.yml for R projects

language: r
warnings_are_errors: true

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2

addons:
  apt:
    packages:
      - libgdal-dev
      - libgdal1-dev
      - libproj-dev
      - libudunits2-dev
  brew_packages:
      - udunits

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

branches:
  only:
    - master
    - develop

r_packages:
  - devtools

r_github_packages:
  - jimhester/covr
  - cran/survival

after_success:
  - Rscript -e 'covr::coveralls()'
