# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: true

matrix:
  include:   
    - os: linux
      dist: trusty
      sudo: false
      r: devel
    - os: linux
      dist: trusty
      sudo: false
      r: release
    - os: linux
      dist: trusty
      sudo: false
      r: oldrel
    - os: osx
      r: release

addons:
  apt:
    packages:
      - libgdal-dev
      - libgdal1-dev
      - libproj-dev
      - libudunits2-dev
  brew_packages:
      - udunits

before_install:
  - if [ ${TRAVIS_OS_NAME} == linux ]; then sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes; fi
  - if [ ${TRAVIS_OS_NAME} == linux ]; then sudo apt-get --yes --force-yes update -qq; fi
  - if [ ${TRAVIS_OS_NAME} == linux ]; then sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev; fi

branches:
  only:
    - master
    - develop

r_packages:
  - devtools

r_github_packages:
  - jimhester/covr
  - cran/survival

after_success:
  - Rscript -e 'covr::coveralls()'
  
script:
  - R CMD build .
  - R CMD check *tar.gz
  - Rscript -e 'install.packages("pkgdown"); pkgdown::build_site()'
